import test from 'node:test';
import assert from 'node:assert/strict';
import {detectionCatalog,publicZones,ruleError,trialMetrics,jpnCoverage} from '../app/surveillance-data.ts';
import {conceptModules,fieldsForTopic} from '../app/concept-data.ts';
test('catalog distinguishes video candidates, sensors and staff reports',()=>{assert.equal(detectionCatalog.length,24);assert.equal(new Set(detectionCatalog.map(c=>c.id)).size,24);for(const c of detectionCatalog)assert.ok(c.limits&&c.response&&c.source);for(const id of ['cheating','truancy','wellbeing'])assert.equal(detectionCatalog.find(c=>c.id===id).kind,'Staff report');});
test('public-area rules reject unsupported placement and malformed values',()=>{const r={zone:publicZones[0],priority:'High',threshold:80,hold:5,schedule:'School hours',reviewer:'Duty staff',publicOnly:true};assert.equal(ruleError(r),'');for(const patch of [{zone:'Toilet'},{publicOnly:false},{threshold:NaN},{hold:-1},{reviewer:'  '},{priority:'Unknown'},{schedule:'Unknown'}])assert.ok(ruleError({...r,...patch}));});
test('evaluation separates precision, recall, missed events and latency',()=>{const base={id:'x',school:'A',capability:'fall',condition:'Day'};const m=trialMetrics([{...base,truth:true,alert:true,latency:9},{...base,truth:true,alert:true,latency:12},{...base,truth:false,alert:true,latency:4},{...base,truth:true,alert:false,latency:0},{...base,truth:false,alert:false,latency:0}]);assert.equal(m.tp,2);assert.equal(m.fp,1);assert.equal(m.fn,1);assert.equal(m.tn,1);assert.equal(m.precision,2/3);assert.equal(m.recall,2/3);assert.equal(m.p95,12);});
test('empty evaluation never implies a perfect result',()=>{assert.deepEqual(trialMetrics([]),{tp:0,fp:0,fn:0,tn:0,precision:null,recall:null,p95:null});});
test('pilot governance covers consent, commissioning and authority agreements',()=>{const m=conceptModules.find(m=>m.id==='pilot-governance');assert.equal(m.topics.length,9);const fields=fieldsForTopic(m,'Participation & parental consent');assert.ok(fields.find(f=>f.key==='consent').options.includes('Withdrawn'));assert.equal(jpnCoverage.length,13);});

test('pilot completion requires a resolved decision and supporting fields',async()=>{const {makeConceptSeeds,conceptAdvanceError}=await import('../app/concept-data.ts');const m=conceptModules.find(m=>m.id==='pilot-governance');const r={...makeConceptSeeds(['A']).find(r=>r.module===m.id),stage:m.stages.length-2,checked:[...m.checks]};assert.match(conceptAdvanceError(r,m,'Reviewed the supporting record'),/Resolve the review decision/);r.values={...r.values,decision:'Agreed for demonstration'};assert.match(conceptAdvanceError(r,m,'Reviewed the supporting record'),/supporting pilot fields/);for(const f of fieldsForTopic(m,r.topic))r.values[f.key]=r.values[f.key]||f.options?.[0]||'DEMO reference';assert.equal(conceptAdvanceError(r,m,'Reviewed the supporting record'),'');});
