import { detectionCatalog, type DetectionCapability } from './surveillance-data.ts';

// Industry registry. Each industry supplies its own vocabulary, monitorable
// zones, explicitly excluded private spaces, detection capability register and
// excluded-capability list. Detection registers are industry-specific on
// purpose: a capability that is well evidenced in a warehouse aisle is not
// automatically valid in a hospital corridor.

export type IndustryId =
  | 'education'
  | 'healthcare'
  | 'aged-care'
  | 'retail'
  | 'construction'
  | 'industrial'
  | 'transport'
  | 'commercial';

export type Lexicon = {
  /** One monitored organisation, e.g. "school", "hospital", "store". */
  site: string;
  sitePlural: string;
  /** Title-case label used in headings. */
  siteTitle: string;
  /** The people the site serves and owes a duty of care to. */
  person: string;
  personPlural: string;
  /** The responding workforce. */
  staff: string;
  /** Default duty/review team named on a saved rule. */
  reviewTeam: string;
  /** Operating-hours label used by the rule scheduler. */
  hours: string;
};

export type ExcludedCapability = { name: string; why: string };

export type Industry = {
  id: IndustryId;
  name: string;
  sector: string;
  tagline: string;
  lexicon: Lexicon;
  /** Primary regulator or standard-setter for the operating context. */
  regulator: string;
  /** Areas the platform is willing to place a camera rule in. */
  zones: string[];
  /** Areas explicitly excluded from camera monitoring in this industry. */
  privateZones: string[];
  /** Incident categories used by filters, routing and analytics. */
  categories: string[];
  capabilities: DetectionCapability[];
  excluded: ExcludedCapability[];
  keyRisks: string[];
  /** Demonstration sites. */
  sites: string[];
  /** Concept workspace module ids available for this industry. */
  modules: string[];
  /** Whether the education-specific presence register applies. */
  presence: boolean;
};

const d = (
  id: string,
  name: string,
  kind: DetectionCapability['kind'],
  priority: DetectionCapability['priority'],
  scene: string,
  signal: string,
  limits: string,
  response: string,
  source: string,
): DetectionCapability => ({
  id,
  name,
  kind,
  priority,
  scene,
  signal,
  limits,
  response,
  source,
});

// Shared evidence sources.
const axis = 'https://help.axis.com/en-us/axis-object-analytics';
const ipro =
  'https://i-pro.com/products_and_solutions/en/surveillance/newsroom/i-pro-introduces-industrys-first-ai-scene-change-detection-capability';
const hanwha =
  'https://www.hanwhavision.com/wp-content/uploads/2026/01/White-Paper_Slip-and-fall-detection.pdf';
const bosch =
  'https://catalog.boschbuildingtechnologies.com/lifesafetysystems/en/Video-based-Fire-Detection/c/22570758923';
const halo = 'https://halodetect.com/';
const workflow = 'Operational workflow requirement';
const healthcareSrc =
  'https://securitytoday.com/articles/2026/08/26/ai-video-analytics-transform-healthcare-safety-and-patient-monitoring.aspx';
const nnu =
  'https://www.nationalnursesunited.org/the-state-of-workplace-violence-in-health-care-in-2025-2026';
const agedCareSrc = 'https://arxiv.org/pdf/2505.18242';
const dignitySrc = 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12411420/';
const ppeSrc = 'https://www.smartqhse.com/safety-blog/computer-vision-ppe-compliance-detection';
const constructionVlm = 'https://arxiv.org/pdf/2605.19869';
const forkliftSrc = 'https://www.spot.ai/blog/forklift-pedestrian-safety-video-ai';
const baggageSrc = 'https://videoraiq.com/blog/unattended-baggage-detection-2026-airport-guide/';
const transitSrc = 'https://visionplatform.ai/ai-video-analytics-for-train-stations/';
const retailFrPrinciples = 'https://ecrloss.com/facial-recognition-in-retail-guidelines/';

// Capabilities that genuinely generalise across every monitored estate.
// Each industry re-states them with its own zone language rather than
// inheriting a school-shaped description.
const serviceHealth = (scene: string, patrol: string) => [
  d(
    'tamper',
    'Camera obstruction / scene shift',
    'Sensor integration',
    'High',
    scene,
    'Feed health or view change suggests impaired coverage.',
    'Dirt, lighting, weather or maintenance may cause the event; intent is unknown.',
    patrol,
    axis,
  ),
  d(
    'stale',
    'Stale feed / connection loss',
    'Sensor integration',
    'High',
    scene,
    'Capture timestamps stop advancing or the connection drops.',
    'A network failure is not a normal or all-clear scene and must never read as a quiet area.',
    'Mark coverage unavailable and start the fallback patrol.',
    axis,
  ),
];

export const industries: Industry[] = [
  // ------------------------------------------------------------------ 1
  {
    id: 'education',
    name: 'Education',
    sector: 'Schools, boarding schools and campuses',
    tagline:
      'Safeguarding, incident review and duty-of-care records for school estates.',
    lexicon: {
      site: 'school',
      sitePlural: 'schools',
      siteTitle: 'School',
      person: 'pupil',
      personPlural: 'pupils',
      staff: 'school staff',
      reviewTeam: 'School duty team',
      hours: 'School hours',
    },
    regulator: 'Ministry of Education Malaysia · PDPA (Amendment) Act 2024',
    zones: [
      'Main gate',
      'Canteen',
      'Block A corridor',
      'East perimeter',
      'Courtyard',
      'Assembly hall',
      'Hostel common lobby',
    ],
    privateZones: [
      'Dormitory bedrooms',
      'Bathrooms and toilets',
      'Changing rooms',
      'Counselling rooms',
    ],
    categories: [
      'Restricted area intrusion',
      'Crowd counting',
      'Entry / exit counting',
      'Unusual dwell time',
      'Possible fall',
      'Possible physical altercation',
      'Visible blade concern',
      'Blocked exit',
      'Unattended item',
      'Vehicles at drop-off / pick-up',
      'Safeguarding concern',
      'Welfare concern',
    ],
    capabilities: detectionCatalog,
    excluded: [
      {
        name: 'Facial recognition and pupil watchlists',
        why: 'Biometric data is sensitive personal data under the amended PDPA and MOE excludes biometrics from the school programme.',
      },
      {
        name: 'Emotion, distress or violence-prediction inference',
        why: 'No validated basis exists. Wellbeing belongs in the confidential support pathway.',
      },
      {
        name: 'Automated escalation from an AI alert to police',
        why: 'An unvalidated label must never trigger an armed response to a child.',
      },
      {
        name: 'Gaze or posture-based cheating classifiers',
        why: 'Exam integrity is an invigilation process with an appeal route.',
      },
      {
        name: 'Cameras in dormitories, bathrooms or changing rooms',
        why: 'Prohibited by MOE policy. Verified warden rounds are the control.',
      },
    ],
    keyRisks: [
      'Bullying, intimidation and retaliation after reporting',
      'Hostel supervision overnight, where cameras are correctly prohibited',
      'Unverified pupil handover at gates and transport',
      'Blocked escape routes and facilities defects',
    ],
    sites: ['SMK Tunku Ampuan Durah', 'SK Seremban Jaya'],
    modules: [
      'pilot-governance',
      'safeguarding',
      'emergency-centre',
      'hostel-operations',
      'movement-visitors',
      'activities-continuity',
      'platform-readiness',
    ],
    presence: true,
  },

  // ------------------------------------------------------------------ 2
  {
    id: 'healthcare',
    name: 'Healthcare',
    sector: 'Hospitals, emergency departments and clinics',
    tagline:
      'Staff safety, patient welfare and restricted-area control across clinical estates.',
    lexicon: {
      site: 'hospital',
      sitePlural: 'hospitals',
      siteTitle: 'Hospital',
      person: 'patient',
      personPlural: 'patients',
      staff: 'clinical staff',
      reviewTeam: 'Security & nurse-in-charge',
      hours: 'Day shift',
    },
    regulator:
      'Ministry of Health Malaysia · Private Healthcare Facilities Act · PDPA',
    zones: [
      'Main entrance',
      'Emergency department waiting',
      'Ward corridor',
      'Pharmacy store entrance',
      'Ambulance bay',
      'Records store corridor',
      'Staff car park',
    ],
    privateZones: [
      'Patient bays and bed spaces',
      'Consultation and examination rooms',
      'Operating theatres',
      'Toilets, bathrooms and changing rooms',
      'Staff rest rooms',
    ],
    categories: [
      'Aggression toward staff',
      'Patient fall',
      'Unaccompanied departure',
      'Department crowding',
      'Restricted area intrusion',
      'Ambulance bay obstruction',
      'Blocked exit',
      'Unattended item',
      'Floor hazard',
      'Patient safety incident',
      'Welfare concern',
    ],
    capabilities: [
      d(
        'aggression',
        'Aggression toward staff',
        'Video candidate',
        'Critical',
        'ed-waiting',
        'Rapid close interaction or raised-posture activity at a reception or triage point.',
        'Motion cannot establish intent, assault or culpability. Distress, pain and crowding produce similar movement. Never treat as proof of an offence.',
        'Send security support and protect staff; review with the person, not about them.',
        nnu,
      ),
      d(
        'fall',
        'Patient fall / person down',
        'Video candidate',
        'Critical',
        'ward-corridor',
        'A posture transition or person-down candidate in a public clinical corridor.',
        'Sitting, prayer, assisted mobilisation and occlusion confuse the model. Not a clinical assessment.',
        'Send the nearest clinical responder and record a patient safety incident.',
        hanwha,
      ),
      d(
        'elopement',
        'Unaccompanied departure from a ward area',
        'Video candidate',
        'High',
        'ward-corridor',
        'A track crosses a ward-boundary line during a restricted period.',
        'Cannot identify who left, or whether departure was authorised. Visitors and discharges cross the same line.',
        'Check the ward register and initiate the missing-patient procedure if unresolved.',
        healthcareSrc,
      ),
      d(
        'crowd',
        'Department crowding & queue pressure',
        'Video candidate',
        'High',
        'ed-waiting',
        'Visible occupancy in a waiting area exceeds a threshold for a set period.',
        'A count is an estimate from one view; it is not a triage list and cannot measure acuity.',
        'Open overflow capacity and update waiting information.',
        axis,
      ),
      d(
        'waitwelfare',
        'Prolonged wait without staff contact',
        'Video candidate',
        'Medium',
        'ed-waiting',
        'An anonymous track remains in a waiting area beyond a welfare-check interval.',
        'Companions, discharged patients and staff produce the same signal. Not a clinical deterioration alert.',
        'Arrange a welfare and re-triage check.',
        axis,
      ),
      d(
        'restricted',
        'Restricted clinical area entry',
        'Video candidate',
        'High',
        'records-corridor',
        'A track enters a pharmacy store, records store or theatre corridor outside its schedule.',
        'A crossing does not establish identity or permission; contractors and porters are legitimate.',
        'Verify authorisation against the access log.',
        axis,
      ),
      d(
        'tailgate',
        'Close-following at a controlled door',
        'Video candidate',
        'Medium',
        'records-corridor',
        'Two tracks cross a controlled entrance within a short interval on one badge event.',
        'Legitimate group entry, trolleys and wheelchair assistance look identical without access data.',
        'Correlate with the access-control event before acting.',
        axis,
      ),
      d(
        'ambulance',
        'Ambulance bay obstruction',
        'Video candidate',
        'Critical',
        'ambulance-bay',
        'A vehicle or object dwells in the marked ambulance bay beyond its permitted period.',
        'Perspective is not a calibrated measurement; active handovers legitimately occupy the bay.',
        'Clear the bay and notify the duty controller.',
        axis,
      ),
      d(
        'exit',
        'Blocked exit or corridor obstruction',
        'Video candidate',
        'High',
        'ward-corridor',
        'A persistent scene change appears in a marked escape route.',
        'Not a certified fire-safety inspection. Beds and equipment in transit are normal.',
        'Verify the route and clear the obstruction safely.',
        ipro,
      ),
      d(
        'spill',
        'Floor hazard / spill',
        'Video candidate',
        'Medium',
        'hosp-entrance',
        'A persistent scene change appears on a walked surface.',
        'Shadows, cleaning in progress and floor markings create false candidates.',
        'Send housekeeping and place a hazard sign.',
        ipro,
      ),
      d(
        'left',
        'Unattended item',
        'Video candidate',
        'Medium',
        'ed-waiting',
        'An object remains after the person who placed it leaves the view.',
        'Cannot determine ownership or contents. Patient belongings are common.',
        'Ask staff to assess using the site protocol.',
        ipro,
      ),
      d(
        'blade',
        'Visible weapon-like object',
        'Video candidate',
        'Critical',
        'ward-corridor',
        'A visible object may resemble a blade or weapon.',
        'Experimental candidate. Clinical instruments, tools and props are easily confused. Concealed objects are not detectable.',
        'Human verification first; follow the security protocol. Never auto-escalate externally.',
        'https://arxiv.org/abs/2303.10703',
      ),
      d(
        'doorheld',
        'Secure door held open',
        'Sensor integration',
        'High',
        'records-corridor',
        'A door contact on a maternity, paediatric or drug-store door remains open beyond its allowed period.',
        'Requires a real door contact. Deliveries and cleaning create legitimate exceptions.',
        'Check the door and the approved schedule.',
        ipro,
      ),
      d(
        'hygiene',
        'Hand-hygiene station usage (aggregate)',
        'Sensor integration',
        'Medium',
        'pharmacy-door',
        'Dispenser events per zone per shift, reported only as an aggregate rate.',
        'Never attributed to an individual. Aggregate usage is not compliance and not a competence measure.',
        'Review provision, placement and stock with the infection-control lead.',
        workflow,
      ),
      d(
        'smoke',
        'Smoke / flame warning',
        'Sensor integration',
        'Critical',
        'ambulance-bay',
        'An approved fire device or specialist video system sends a warning.',
        'Ordinary CCTV is not a substitute for an approved fire detection system.',
        'Follow the site fire procedure.',
        bosch,
      ),
      d(
        'plant',
        'Medical gas / plant room intrusion',
        'Video candidate',
        'High',
        'records-corridor',
        'A track enters a plant or medical-gas area outside a maintenance window.',
        'Authorised engineers use the same route; the permit system is the source of truth.',
        'Verify the permit to work before responding.',
        axis,
      ),
      d(
        'lone',
        'Lone worker in a low-traffic area',
        'Video candidate',
        'Medium',
        'hosp-carpark',
        'A single track is present in a low-traffic area outside staffed hours.',
        'Presence is not distress. Cannot confirm whether the person is well.',
        'Make contact and confirm welfare.',
        axis,
      ),
      ...serviceHealth(
      'records-corridor', 'Arrange a patrol and maintenance check.'),
      d(
        'violence-report',
        'Workplace violence report',
        'Staff report',
        'High',
        'records-corridor',
        'A staff member records an abuse, threat or assault incident.',
        'Under-reporting is the norm in healthcare; absence of reports is not absence of harm.',
        'Support the staff member, record the incident and follow the escalation policy.',
        nnu,
      ),
      d(
        'safety-incident',
        'Patient safety incident',
        'Staff report',
        'High',
        'ward-corridor',
        'Clinical staff record a fall, medication or care incident for review.',
        'A reporting category, not an added detector. No clinical inference is made from video.',
        'Follow the incident review and duty-of-candour process.',
        workflow,
      ),
      d(
        'wellbeing',
        'Welfare or safeguarding concern',
        'Staff report',
        'High',
        'hosp-carpark',
        'A patient, relative or staff member requests support.',
        'No emotion, diagnosis, intent or risk inference is made from video.',
        'Use the confidential safeguarding and support route.',
        workflow,
      ),
    ],
    excluded: [
      {
        name: 'Cameras in patient bays, consultation rooms or theatres',
        why: 'Clinical care is a private act. Bed-exit monitoring in a bay is a bedside sensor decision with consent, not an estate camera rule.',
      },
      {
        name: 'Facial recognition of patients, visitors or staff',
        why: 'Biometric data is sensitive personal data under the amended PDPA, and health context raises the harm from error.',
      },
      {
        name: 'Pain, emotion or deterioration inference from video',
        why: 'No validated basis. Clinical observation and early-warning scores are the established instruments.',
      },
      {
        name: 'Individual staff performance or hand-hygiene scoring',
        why: 'Aggregate station usage is an infection-control signal; per-person scoring converts a safety tool into surveillance of the workforce.',
      },
      {
        name: 'Automatic security or police dispatch from an aggression candidate',
        why: 'Distress in an emergency department is not assault. A human decides.',
      },
    ],
    keyRisks: [
      'Assault and abuse directed at emergency and ward staff',
      'Patient falls in corridors and waiting areas',
      'Unaccompanied departure from ward areas',
      'Controlled-drug and records-store access',
      'Ambulance bay and escape-route obstruction',
    ],
    sites: ['Hospital Seremban', 'Klinik Kesihatan Senawang'],
    modules: ['pilot-governance', 'platform-readiness'],
    presence: false,
  },

  // ------------------------------------------------------------------ 3
  {
    id: 'aged-care',
    name: 'Aged & residential care',
    sector: 'Care homes and assisted living',
    tagline:
      'Resident welfare in communal areas, with dignity limits designed in.',
    lexicon: {
      site: 'care home',
      sitePlural: 'care homes',
      siteTitle: 'Care home',
      person: 'resident',
      personPlural: 'residents',
      staff: 'care staff',
      reviewTeam: 'Shift lead & registered nurse',
      hours: 'Day shift',
    },
    regulator:
      'Jabatan Kebajikan Masyarakat · Care Centres Act 1993 · PDPA',
    zones: [
      'Main entrance',
      'Lounge',
      'Dining room',
      'Resident corridor',
      'Garden and courtyard',
      'Laundry corridor',
      'Visitor car park',
    ],
    privateZones: [
      'Resident bedrooms',
      'Bathrooms and toilets',
      'Personal care areas',
      'Treatment rooms',
    ],
    categories: [
      'Resident fall',
      'Prolonged floor presence',
      'Exit-seeking',
      'Night corridor activity',
      'Distress or altercation',
      'Blocked exit',
      'Trip hazard',
      'Out-of-hours visitor',
      'Welfare check',
    ],
    capabilities: [
      d(
        'fall',
        'Fall / person down in a communal area',
        'Video candidate',
        'Critical',
        'care-corridor',
        'A posture transition or person-down candidate in a lounge, dining room or corridor.',
        'Sitting on low furniture, assisted transfers and occlusion confuse the model. It is not a clinical assessment of injury.',
        'Send the nearest carer and complete a post-fall check.',
        hanwha,
      ),
      d(
        'floor',
        'Prolonged floor presence (unwitnessed fall)',
        'Video candidate',
        'Critical',
        'care-corridor',
        'A track remains at floor level beyond a short persistence threshold.',
        'Exercise, prayer and dropped-item retrieval produce the same signal. Long lie times are the harm this targets.',
        'Attend immediately and record the time the resident was found.',
        hanwha,
      ),
      d(
        'exitseek',
        'Exit-seeking at a boundary door',
        'Video candidate',
        'High',
        'care-garden',
        'A track approaches or crosses an external door outside supervised hours.',
        'Cannot identify the resident or distinguish a visitor leaving. Exit-seeking is a care need, not misconduct.',
        'Redirect gently, check welfare and review the care plan.',
        dignitySrc,
      ),
      d(
        'night',
        'Night-time corridor activity',
        'Video candidate',
        'Medium',
        'care-corridor',
        'Movement in a resident corridor during night hours above a baseline.',
        'Normal night waking, toileting and staff rounds all register. This is a prompt, never an alarm about a person.',
        'Fold into the next welfare round rather than waking the resident.',
        axis,
      ),
      d(
        'distress',
        'Distress or altercation between residents',
        'Video candidate',
        'High',
        'care-lounge',
        'Rapid close interaction in a communal area.',
        'Distress in dementia care is a symptom, not misconduct. Video cannot establish blame, intent or a safeguarding conclusion.',
        'Separate calmly, check welfare and record a behaviour-support note.',
        dignitySrc,
      ),
      d(
        'bathroom',
        'Bathroom emergency (camera-free sensor)',
        'Sensor integration',
        'Critical',
        'care-corridor',
        'A presence and inactivity sensor in a bathroom reports no movement beyond a threshold.',
        'Deliberately camera-free to preserve dignity. Sensors miss quiet, still occupancy and need calibration per room.',
        'Knock, announce and check; escalate to the nurse on duty.',
        agedCareSrc,
      ),
      d(
        'doorheld',
        'Secure door held open',
        'Sensor integration',
        'High',
        'care-entrance',
        'A door contact on a secure boundary remains open beyond its allowed period.',
        'Requires a real door contact. Deliveries and visitor arrivals are legitimate exceptions.',
        'Check the door and confirm all residents are accounted for.',
        ipro,
      ),
      d(
        'exit',
        'Blocked exit / escape route',
        'Video candidate',
        'High',
        'care-entrance',
        'A persistent scene change appears in a marked escape route.',
        'Not a certified fire-safety inspection. Mobility aids in transit are normal.',
        'Clear the route and record the check.',
        ipro,
      ),
      d(
        'trip',
        'Trip hazard / obstruction',
        'Video candidate',
        'Medium',
        'care-laundry',
        'A persistent object or spill appears on a walked surface.',
        'Shadows and floor patterns create false candidates; a hazard is not proof of neglect.',
        'Remove the hazard and log it against the environment check.',
        ipro,
      ),
      d(
        'visitor',
        'Out-of-hours visitor arrival',
        'Video candidate',
        'Medium',
        'care-entrance',
        'A track crosses the entrance during an unstaffed reception period.',
        'Family visits, agency staff and deliveries are all legitimate. Never identifies the visitor.',
        'Greet, verify at reception and record the visit.',
        axis,
      ),
      d(
        'smoke',
        'Smoke / flame warning',
        'Sensor integration',
        'Critical',
        'care-entrance',
        'An approved fire device or specialist video system sends a warning.',
        'Ordinary CCTV is not an approved fire detection system, and evacuation of frail residents is slow.',
        'Follow the progressive-horizontal-evacuation procedure.',
        bosch,
      ),
      ...serviceHealth(
      'care-laundry', 'Arrange a patrol and maintenance check.'),
      d(
        'welfare-round',
        'Welfare round verification',
        'Staff report',
        'High',
        'care-lounge',
        'A carer records a completed round with time and location.',
        'A recorded round is evidence of a check, not of a resident being well.',
        'Escalate any missed round to the shift lead.',
        workflow,
      ),
      d(
        'safeguarding',
        'Safeguarding or dignity concern',
        'Staff report',
        'High',
        'care-dining',
        'A resident, relative or staff member raises a concern.',
        'No emotion, cognitive-decline or capacity inference is made from video.',
        'Follow the adult safeguarding referral route.',
        dignitySrc,
      ),
    ],
    excluded: [
      {
        name: 'Cameras in bedrooms, bathrooms or personal care areas',
        why: 'Dignity is the primary duty. Where in-room monitoring is genuinely needed it is a consented, resident-led decision with a camera-free sensor, not an estate rule.',
      },
      {
        name: 'Facial recognition of residents, families or staff',
        why: 'Biometric data is sensitive personal data, and residents may lack capacity to consent meaningfully.',
      },
      {
        name: 'Cognitive-decline, mood or agitation scoring from video',
        why: 'No validated basis, and it converts a symptom into a permanent record about a person.',
      },
      {
        name: 'Continuous recording of personal care',
        why: 'Never proportionate. Care quality is assured by supervision, training and reporting.',
      },
    ],
    keyRisks: [
      'Unwitnessed falls and long lie times in communal areas',
      'Exit-seeking and wandering at boundary doors',
      'Overnight supervision when staffing is thinnest',
      'Slow evacuation of residents with limited mobility',
    ],
    sites: ['Rumah Seri Kenangan', 'Taman Sri Damai Care Residence'],
    modules: ['pilot-governance', 'platform-readiness'],
    presence: false,
  },

  // ------------------------------------------------------------------ 4
  {
    id: 'retail',
    name: 'Retail',
    sector: 'Stores, supermarkets and shopping centres',
    tagline:
      'Colleague safety, queue and hazard management, without profiling shoppers.',
    lexicon: {
      site: 'store',
      sitePlural: 'stores',
      siteTitle: 'Store',
      person: 'customer',
      personPlural: 'customers',
      staff: 'colleagues',
      reviewTeam: 'Duty manager',
      hours: 'Trading hours',
    },
    regulator: 'PDPA (Amendment) Act 2024 · consumer and workplace safety law',
    zones: [
      'Shopfront entrance',
      'Checkout area',
      'Main aisle',
      'Stockroom door',
      'Loading bay',
      'Back corridor',
      'Customer car park',
    ],
    privateZones: [
      'Fitting rooms',
      'Toilets',
      'Staff rest rooms and lockers',
      'First-aid room',
    ],
    categories: [
      'Aggression toward colleagues',
      'Queue pressure',
      'Restricted area intrusion',
      'Secured display change',
      'Slip or fall',
      'Floor hazard',
      'Blocked exit',
      'After-hours presence',
      'Loading bay conflict',
      'Theft report',
    ],
    capabilities: [
      d(
        'aggression',
        'Aggression toward colleagues',
        'Video candidate',
        'Critical',
        'shop-entrance',
        'Rapid close interaction at a checkout, service desk or entrance.',
        'Motion cannot establish intent, threat or an offence. Animated conversation looks similar.',
        'Send a manager, support the colleague and record the incident.',
        nnu,
      ),
      d(
        'queue',
        'Queue length & wait pressure',
        'Video candidate',
        'High',
        'retail-checkout',
        'People waiting in a checkout zone exceed a threshold for a set period.',
        'A count is an estimate from one view and cannot see abandoned baskets.',
        'Open another till and reassign colleagues.',
        axis,
      ),
      d(
        'footfall',
        'Occupancy & footfall counting',
        'Video candidate',
        'Medium',
        'shop-entrance',
        'Anonymous entry and exit counts at a doorway.',
        'Entry-minus-exit drifts when doors are unobserved. It is an estimate, never an identified visit.',
        'Use for staffing and layout decisions only.',
        axis,
      ),
      d(
        'restricted',
        'Restricted area entry',
        'Video candidate',
        'High',
        'stockroom-door',
        'A track enters a stockroom, cash office or back corridor.',
        'A crossing does not establish identity or permission. Colleagues and contractors use the same route.',
        'Verify against the rota and access log.',
        axis,
      ),
      d(
        'tailgate',
        'Close-following at a staff door',
        'Video candidate',
        'Medium',
        'shop-entrance',
        'Two tracks cross a controlled door within a short interval.',
        'Colleagues holding a door for each other is normal and looks identical.',
        'Correlate with the access event before acting.',
        axis,
      ),
      d(
        'dwell',
        'Prolonged dwell at a secured display',
        'Video candidate',
        'Medium',
        'retail-checkout',
        'An anonymous track remains at a high-value display beyond a dwell threshold.',
        'Dwell is not theft and never identifies a person. Browsing, indecision, disability and waiting all produce it. Must not create a record about an individual.',
        'Offer service. Do not approach anyone as a suspect on this signal alone.',
        retailFrPrinciples,
      ),
      d(
        'removed',
        'Secured display change / stock removal',
        'Video candidate',
        'High',
        'stockroom-door',
        'A protected display scene changes materially.',
        'Removal may be authorised replenishment; CCTV cannot establish theft or identify who acted.',
        'Check replenishment records before any loss classification.',
        ipro,
      ),
      d(
        'fall',
        'Slip / fall in a trading area',
        'Video candidate',
        'High',
        'retail-aisle',
        'A posture transition or person-down candidate on the shop floor.',
        'Crouching to low shelves and children playing confuse the model. Not a medical assessment.',
        'Send first aid and record the incident and scene condition.',
        hanwha,
      ),
      d(
        'spill',
        'Floor hazard / spill',
        'Video candidate',
        'Medium',
        'retail-aisle',
        'A persistent scene change appears on a walked surface.',
        'Shadows, wet-floor signs and floor graphics create false candidates.',
        'Send cleaning and place a hazard sign.',
        ipro,
      ),
      d(
        'exit',
        'Blocked fire exit',
        'Video candidate',
        'High',
        'retail-back',
        'A persistent scene change appears in a marked escape route.',
        'Not a certified fire-safety inspection; delivery cages in transit are normal.',
        'Clear the route and record the check.',
        ipro,
      ),
      d(
        'left',
        'Unattended item',
        'Video candidate',
        'Medium',
        'retail-aisle',
        'An object remains after the person who placed it leaves the view.',
        'Cannot determine ownership or contents. Lost property is the common case.',
        'Follow the lost-property and security protocol.',
        ipro,
      ),
      d(
        'afterhours',
        'After-hours presence',
        'Video candidate',
        'High',
        'stockroom-door',
        'Presence is detected during a closed period.',
        'Cleaning, replenishment and maintenance are scheduled exceptions.',
        'Verify against the out-of-hours works schedule.',
        axis,
      ),
      d(
        'dock',
        'Loading bay vehicle / pedestrian conflict',
        'Video candidate',
        'High',
        'retail-dock',
        'A pedestrian track enters a marked vehicle movement area.',
        'Perspective is not a calibrated distance or speed measurement.',
        'Separate traffic and pedestrians; review the bay marshalling plan.',
        axis,
      ),
      d(
        'obstruction',
        'Aisle obstruction',
        'Video candidate',
        'Low',
        'retail-aisle',
        'A cage, pallet or display remains in an aisle beyond a threshold.',
        'Active replenishment is legitimate and temporary.',
        'Create a housekeeping task; no individual sanction.',
        ipro,
      ),
      d(
        'smoke',
        'Smoke / flame warning',
        'Sensor integration',
        'Critical',
        'retail-dock',
        'An approved fire device or specialist video system sends a warning.',
        'Ordinary CCTV is not an approved fire detection system.',
        'Follow the store evacuation procedure.',
        bosch,
      ),
      ...serviceHealth(
      'retail-back', 'Arrange a patrol and maintenance check.'),
      d(
        'theft-report',
        'Theft or loss report',
        'Staff report',
        'High',
        'retail-back',
        'A colleague records a suspected loss for investigation.',
        'A reporting category, not an added detector. No shopper is classified by the system.',
        'Follow the loss investigation and evidence process.',
        workflow,
      ),
      d(
        'age-refusal',
        'Age-restricted sale refusal',
        'Staff report',
        'Low',
        'stockroom-door',
        'A colleague records a challenge and refusal for the compliance log.',
        'No age-estimation model is enabled. Judgement and ID remain the control.',
        'File in the refusals register for licensing review.',
        workflow,
      ),
      d(
        'colleague-safety',
        'Colleague safety concern',
        'Staff report',
        'High',
        'retail-carpark',
        'A colleague reports abuse, threat or an unsafe situation.',
        'Retail violence is heavily under-reported; a low count is not a safe store.',
        'Support the colleague and follow the escalation policy.',
        nnu,
      ),
    ],
    excluded: [
      {
        name: 'Facial recognition and shopper watchlists',
        why: 'Real-time biometric identification in publicly accessible spaces is high-risk under the EU AI Act, several jurisdictions moved to ban retail facial recognition through 2026, and biometrics are sensitive personal data under the amended PDPA.',
      },
      {
        name: 'Demographic, appearance or "suspicion score" profiling',
        why: 'It produces discriminatory outcomes and creates a record about a person who has done nothing.',
      },
      {
        name: 'Emotion or intent inference',
        why: 'No validated basis, and the cost of error falls on innocent customers.',
      },
      {
        name: 'Individual colleague productivity or pace scoring',
        why: 'A safety platform must not become a workforce performance monitor.',
      },
      {
        name: 'Cameras in fitting rooms, toilets or staff rest areas',
        why: 'A reasonable expectation of privacy applies absolutely in these spaces. No shrink figure justifies monitoring a person undressing or on a break.',
      },
    ],
    keyRisks: [
      'Abuse and violence directed at checkout and service colleagues',
      'Slips, trips and falls creating injury and liability',
      'Queue pressure and entrance congestion at peak',
      'Loading bay vehicle and pedestrian conflict',
    ],
    sites: ['Seremban Prima Hypermarket', 'KL Sentral Convenience Store'],
    modules: ['pilot-governance', 'platform-readiness'],
    presence: false,
  },

  // ------------------------------------------------------------------ 5
  {
    id: 'construction',
    name: 'Construction',
    sector: 'Building sites and civil works',
    tagline:
      'PPE, exclusion zones and plant conflict on active sites, with honest accuracy limits.',
    lexicon: {
      site: 'site',
      sitePlural: 'sites',
      siteTitle: 'Site',
      person: 'worker',
      personPlural: 'workers',
      staff: 'site team',
      reviewTeam: 'Site safety officer',
      hours: 'Site hours',
    },
    regulator:
      'DOSH Malaysia · OSHA 1994 (as amended 2022) · CIDB Act 520',
    zones: [
      'Site entrance',
      'Material laydown',
      'Scaffold zone',
      'Excavation edge',
      'Crane radius',
      'Site access road',
      'Welfare cabin area',
    ],
    privateZones: [
      'Welfare cabin interiors',
      'Toilets and drying rooms',
      'Worker accommodation',
    ],
    categories: [
      'Helmet not detected',
      'Hi-vis not detected',
      'Harness concern',
      'Exclusion zone entry',
      'Plant / pedestrian conflict',
      'Unprotected edge',
      'Perimeter intrusion',
      'Blocked emergency route',
      'Lone worker',
      'Near miss',
    ],
    capabilities: [
      d(
        'helmet',
        'Helmet not detected',
        'Video candidate',
        'High',
        'site-scaffold',
        'A person track in a hard-hat area shows no detected helmet.',
        'Reported accuracy is roughly 90–97% in good light and degrades sharply with dust, glare, distance, occlusion and worker clustering. A miss is not proof of non-compliance.',
        'Ask a supervisor to check and re-brief; never sanction on the alert alone.',
        ppeSrc,
      ),
      d(
        'hivis',
        'High-visibility clothing not detected',
        'Video candidate',
        'High',
        'site-scaffold',
        'A person track in a hi-vis area shows no detected vest.',
        'Similar accuracy envelope to helmet detection; colour, weather and lighting dominate results.',
        'Supervisor check and re-brief.',
        ppeSrc,
      ),
      d(
        'harness',
        'Fall-arrest harness concern',
        'Video candidate',
        'Critical',
        'site-scaffold',
        'A person working at height shows no detected harness or anchor.',
        'Experimental. Body-worn equipment detection is materially less accurate than helmet or vest, and anchorage cannot be verified visually at all.',
        'Stop the task, verify anchorage physically and record the check.',
        ppeSrc,
      ),
      d(
        'exclusion',
        'Exclusion zone entry',
        'Video candidate',
        'Critical',
        'site-crane',
        'A track enters an excavation, crane swing radius or live electrical zone.',
        'Zone geometry must be surveyed and kept current as the site changes; a stale zone is worse than none.',
        'Stop the activity and clear the zone.',
        constructionVlm,
      ),
      d(
        'plant',
        'Plant / pedestrian proximity',
        'Video candidate',
        'Critical',
        'site-road',
        'A pedestrian track and a moving plant item converge in a shared area.',
        'Perspective is not a calibrated distance or closing-speed measurement; mixed-traffic zones need per-zone setup.',
        'Halt the movement and enforce the segregation plan.',
        forkliftSrc,
      ),
      d(
        'edge',
        'Presence near an unprotected edge',
        'Video candidate',
        'High',
        'site-excavation',
        'A track approaches a marked leading edge or opening.',
        'Experimental. Depends entirely on an accurately surveyed edge that changes as work progresses.',
        'Verify edge protection and stop work if it is absent.',
        constructionVlm,
      ),
      d(
        'intrusion',
        'Site perimeter intrusion',
        'Video candidate',
        'High',
        'site-entrance',
        'A track crosses the site boundary outside working hours.',
        'A crossing does not establish identity or intent; wildlife and weather create false candidates.',
        'Verify and dispatch the on-call response.',
        axis,
      ),
      d(
        'route',
        'Blocked emergency route',
        'Video candidate',
        'High',
        'site-entrance',
        'A persistent scene change appears in a marked escape or access route.',
        'Not a certified inspection; material movement is continuous on a live site.',
        'Clear the route and record it against the daily check.',
        ipro,
      ),
      d(
        'lone',
        'Lone worker outside site hours',
        'Video candidate',
        'Medium',
        'site-laydown',
        'A single track is present in a work area outside scheduled hours.',
        'Presence is not distress. Permitted out-of-hours works are legitimate.',
        'Contact the worker and confirm the permit and welfare.',
        axis,
      ),
      d(
        'laydown',
        'Material stacking / laydown change',
        'Video candidate',
        'Medium',
        'site-laydown',
        'A material stack changes shape or encroaches on a route.',
        'A changed scene cannot assess load stability or ground bearing.',
        'Physical inspection by the works supervisor.',
        ipro,
      ),
      d(
        'hotworks',
        'Hot works / fire watch',
        'Sensor integration',
        'Critical',
        'site-laydown',
        'A permit-linked sensor or specialist system reports a hot-works condition.',
        'Requires a real permit system; video alone cannot confirm a fire watch is posted.',
        'Verify the permit and the fire watch.',
        bosch,
      ),
      d(
        'dust',
        'Dust / air quality event',
        'Sensor integration',
        'Medium',
        'site-road',
        'An environmental sensor reports a threshold exceedance.',
        'Weather, haul roads and neighbouring works all contribute; no person is identified.',
        'Apply dust suppression and review the method statement.',
        halo,
      ),
      ...serviceHealth(
      'site-road', 'Arrange a patrol and maintenance check.'),
      d(
        'nearmiss',
        'Near-miss report',
        'Staff report',
        'High',
        'site-scaffold',
        'A worker or supervisor records a near miss.',
        'A reporting category, not an added detector. Near-miss volume rising is usually a good sign.',
        'Investigate and feed the finding into the method statement.',
        workflow,
      ),
      d(
        'permit',
        'Permit-to-work check',
        'Staff report',
        'High',
        'site-entrance',
        'A supervisor records a permit verification for a high-risk activity.',
        'A recorded check is evidence of a check, not of a safe condition.',
        'Escalate any activity found running without a valid permit.',
        workflow,
      ),
      d(
        'defect',
        'Plant or equipment defect',
        'Staff report',
        'High',
        'site-road',
        'A worker reports damaged plant, scaffold or equipment.',
        'Cannot be established from a camera view; physical inspection is required.',
        'Quarantine the equipment and raise a maintenance task.',
        workflow,
      ),
    ],
    excluded: [
      {
        name: 'Biometric or facial-recognition site attendance',
        why: 'Biometric data is sensitive personal data under the amended PDPA. Badge or QR muster achieves the same operational result.',
      },
      {
        name: 'Individual worker productivity or idle-time monitoring',
        why: 'A safety camera repurposed as a stopwatch destroys the trust the safety case depends on.',
      },
      {
        name: 'Fatigue, intoxication or emotion inference from video',
        why: 'No validated basis. Fitness for work is managed by supervision and occupational health.',
      },
      {
        name: 'Automated disciplinary action from a PPE alert',
        why: 'Detection degrades badly in dust, glare and clustering. A supervisor verifies before any consequence.',
      },
      {
        name: 'Cameras in welfare cabins, toilets or accommodation',
        why: 'Welfare facilities exist so workers can rest and wash unobserved. Monitoring them would undermine the welfare standard it is meant to protect.',
      },
    ],
    keyRisks: [
      'Struck-by incidents involving plant and pedestrians',
      'Falls from height and unprotected edges',
      'Excavation and crane exclusion-zone breaches',
      'Out-of-hours intrusion and theft on open sites',
    ],
    sites: ['Seremban 2 Mixed Development', 'Nilai Industrial Park Phase 3'],
    modules: ['pilot-governance', 'platform-readiness'],
    presence: false,
  },

  // ------------------------------------------------------------------ 6
  {
    id: 'industrial',
    name: 'Manufacturing & warehousing',
    sector: 'Factories, distribution centres and yards',
    tagline:
      'Vehicle–pedestrian separation, machine-area control and route integrity.',
    lexicon: {
      site: 'facility',
      sitePlural: 'facilities',
      siteTitle: 'Facility',
      person: 'operative',
      personPlural: 'operatives',
      staff: 'operations team',
      reviewTeam: 'Shift supervisor & EHS',
      hours: 'Shift hours',
    },
    regulator: 'DOSH Malaysia · OSHA 1994 (as amended 2022) · FMA 1967',
    zones: [
      'Goods-in dock',
      'Racking aisle',
      'Pick face',
      'Machine cell',
      'Packing line',
      'Yard',
      'Battery charging area',
    ],
    privateZones: [
      'Locker and changing rooms',
      'Toilets',
      'Canteen and rest areas',
      'Occupational health room',
    ],
    categories: [
      'Forklift / pedestrian conflict',
      'Pedestrian in vehicle aisle',
      'Machine cell entry',
      'Racking damage',
      'Blocked route',
      'Dock edge risk',
      'PPE not detected',
      'Floor hazard',
      'Person down',
      'Near miss',
    ],
    capabilities: [
      d(
        'forklift',
        'Forklift / pedestrian proximity',
        'Video candidate',
        'Critical',
        'racking-aisle',
        'A pedestrian track and a powered truck converge in a shared aisle.',
        'Perspective is not a calibrated distance or closing-speed measurement. Untagged pedestrians are the gap this closes, but occlusion by racking is common.',
        'Halt the movement and review the segregation plan for that aisle.',
        forkliftSrc,
      ),
      d(
        'pedaisle',
        'Pedestrian in a vehicle-only aisle',
        'Video candidate',
        'High',
        'racking-aisle',
        'A pedestrian track crosses into a marked vehicle-only route.',
        'Only meaningful where segregation markings are current and enforced.',
        'Redirect to the walkway and review signage.',
        forkliftSrc,
      ),
      d(
        'machine',
        'Machine cell entry while running',
        'Video candidate',
        'Critical',
        'machine-cell',
        'A track enters a guarded cell footprint during a running state.',
        'Must be corroborated by the machine interlock. Video alone must never be the sole guard.',
        'Stop the machine and verify the lock-out procedure.',
        axis,
      ),
      d(
        'racking',
        'Racking damage / scene change',
        'Video candidate',
        'High',
        'racking-aisle',
        'A protected racking upright or bay changes shape or position.',
        'A changed scene cannot assess structural capacity; a rack inspector must.',
        'Cordon the bay and raise a rack inspection.',
        ipro,
      ),
      d(
        'route',
        'Blocked route or fire exit',
        'Video candidate',
        'High',
        'charging-bay',
        'A persistent scene change appears in a marked escape or access route.',
        'Not a certified fire-safety inspection; staged pallets in transit are normal.',
        'Clear the route and record the check.',
        ipro,
      ),
      d(
        'dock',
        'Dock edge / open door risk',
        'Video candidate',
        'High',
        'goods-dock',
        'A dock door is open with no vehicle present, or a track approaches an open edge.',
        'Requires accurate dock geometry and a door state source; weather doors complicate it.',
        'Close the door or fit the barrier before work continues.',
        axis,
      ),
      d(
        'ppe',
        'PPE not detected (hi-vis, hearing)',
        'Video candidate',
        'Medium',
        'goods-dock',
        'A person track in a designated area shows no detected hi-vis or ear defenders.',
        'Roughly 90–97% in good light for vests; ear defenders are materially harder and often occluded.',
        'Supervisor check and re-brief; no automatic sanction.',
        ppeSrc,
      ),
      d(
        'spill',
        'Floor hazard / spill',
        'Video candidate',
        'Medium',
        'charging-bay',
        'A persistent scene change appears on a walked or driven surface.',
        'Shadows, floor markings and pallet wrap create false candidates.',
        'Contain the spill and place hazard signage.',
        ipro,
      ),
      d(
        'fall',
        'Fall / person down',
        'Video candidate',
        'Critical',
        'goods-dock',
        'A posture transition or person-down candidate on the operating floor.',
        'Crouching to low pick faces and maintenance work confuse the model.',
        'Send first aid and stop adjacent vehicle movement.',
        hanwha,
      ),
      d(
        'lone',
        'Lone worker in a machine area',
        'Video candidate',
        'Medium',
        'machine-cell',
        'A single track is present in a machine or high-risk area outside staffed hours.',
        'Presence is not distress; planned maintenance is legitimate.',
        'Confirm the permit and check welfare.',
        axis,
      ),
      d(
        'restricted',
        'Restricted area entry',
        'Video candidate',
        'High',
        'racking-aisle',
        'A track enters a chemical store, plant room or high-voltage area.',
        'A crossing does not establish identity or permission.',
        'Verify the permit to work.',
        axis,
      ),
      d(
        'charging',
        'Battery charging area event',
        'Sensor integration',
        'High',
        'charging-bay',
        'A gas, thermal or air-quality sensor reports a threshold event in the charging area.',
        'Requires a real sensor. Ventilation faults and charger faults present similarly.',
        'Ventilate, isolate the charger and inspect.',
        halo,
      ),
      d(
        'smoke',
        'Smoke / flame warning',
        'Sensor integration',
        'Critical',
        'charging-bay',
        'An approved fire device or specialist video system sends a warning.',
        'Ordinary CCTV is not an approved fire detection system; high-bay storage burns fast.',
        'Follow the site fire and evacuation procedure.',
        bosch,
      ),
      ...serviceHealth(
      'plant-yard', 'Arrange a patrol and maintenance check.'),
      d(
        'nearmiss',
        'Near-miss report',
        'Staff report',
        'High',
        'pick-face',
        'An operative or supervisor records a near miss.',
        'A reporting category, not an added detector.',
        'Investigate and update the traffic management plan.',
        workflow,
      ),
      d(
        'loto',
        'Lock-out / tag-out verification',
        'Staff report',
        'Critical',
        'machine-cell',
        'A supervisor records an isolation check before maintenance.',
        'A recorded check is evidence of a check, not of an isolated machine.',
        'Escalate any maintenance found running without isolation.',
        workflow,
      ),
      d(
        'defect',
        'Equipment or racking defect',
        'Staff report',
        'High',
        'racking-aisle',
        'An operative reports damaged plant, racking or handling equipment.',
        'Structural capacity cannot be established from a camera view.',
        'Quarantine and raise an inspection task.',
        workflow,
      ),
    ],
    excluded: [
      {
        name: 'Individual pick-rate, pace or idle-time monitoring',
        why: 'The single fastest way to lose workforce consent for a safety system, and it is not a safety control.',
      },
      {
        name: 'Biometric time and attendance',
        why: 'Biometric data is sensitive personal data under the amended PDPA; badge muster is sufficient.',
      },
      {
        name: 'Fatigue or intoxication inference from video',
        why: 'No validated basis. Fitness for work is an occupational health process.',
      },
      {
        name: 'Video as the sole machine guard',
        why: 'Guarding is a physical and interlocked control. A camera supplements it and never replaces it.',
      },
      {
        name: 'Cameras in changing rooms, toilets or rest areas',
        why: 'A reasonable expectation of privacy applies absolutely, and no safety case has ever depended on watching a rest break.',
      },
    ],
    keyRisks: [
      'Powered-truck and pedestrian collisions in aisles',
      'Machine-area entry during running states',
      'Racking damage and collapse',
      'Blocked escape routes in high-bay storage',
    ],
    sites: ['Nilai Distribution Centre', 'Senawang Assembly Plant'],
    modules: ['pilot-governance', 'platform-readiness'],
    presence: false,
  },

  // ------------------------------------------------------------------ 7
  {
    id: 'transport',
    name: 'Transport hubs',
    sector: 'Airports, rail and transit interchanges',
    tagline:
      'Crowd safety, platform-edge risk and restricted-side access at scale.',
    lexicon: {
      site: 'hub',
      sitePlural: 'hubs',
      siteTitle: 'Hub',
      person: 'passenger',
      personPlural: 'passengers',
      staff: 'station team',
      reviewTeam: 'Station control room',
      hours: 'Service hours',
    },
    regulator:
      'Ministry of Transport Malaysia · APAD · CAAM · PDPA',
    zones: [
      'Concourse',
      'Platform',
      'Gate hold room',
      'Security queue',
      'Escalator landing',
      'Taxi rank',
      'Restricted-side access door',
      'Perimeter fence',
    ],
    privateZones: [
      'Toilets and baby-change rooms',
      'Prayer rooms',
      'Search and screening booths',
      'Staff rest areas',
    ],
    categories: [
      'Platform edge crossing',
      'Crowd density',
      'Queue pressure',
      'Unattended baggage',
      'Against-flow movement',
      'Restricted-side tailgating',
      'Perimeter intrusion',
      'Escalator incident',
      'Person down',
      'Blocked exit',
    ],
    capabilities: [
      d(
        'platform',
        'Platform edge / safety line crossing',
        'Video candidate',
        'Critical',
        'transit-platform',
        'A track crosses the marked safety line on a platform.',
        'Dense crowds occlude tracks badly at exactly the moment the risk is highest. Staff and authorised track access cross the same line.',
        'Announce, dispatch platform staff and apply the service control procedure.',
        transitSrc,
      ),
      d(
        'crowd',
        'Crowd density & crush risk',
        'Video candidate',
        'Critical',
        'transit-concourse',
        'Estimated density in a zone exceeds a threshold for a set period.',
        'Density is an estimate from one view and cannot measure crush forces or pressure at floor level.',
        'Meter inflow, open alternative routes and hold services if required.',
        axis,
      ),
      d(
        'queue',
        'Queue length at screening',
        'Video candidate',
        'High',
        'security-queue',
        'People waiting in a screening zone exceed a threshold for a set period.',
        'A count is an estimate and cannot see lane closures or staffing state.',
        'Open lanes and update passenger information.',
        transitSrc,
      ),
      d(
        'baggage',
        'Unattended baggage',
        'Video candidate',
        'High',
        'security-queue',
        'An item remains without an associated person beyond a configurable period.',
        'Vendor accuracy figures come from their own conditions. Crowding, trolleys and seated passengers create false candidates; an unattended bag is not a threat.',
        'Follow the unattended-item protocol; a human decides on any escalation.',
        baggageSrc,
      ),
      d(
        'wrongway',
        'Movement against one-way flow',
        'Video candidate',
        'High',
        'transit-concourse',
        'A track crosses a directional line against the configured flow.',
        'Only meaningful while a one-way plan is active; disruption and evacuation invert normal flow.',
        'Send a steward to manage the flow.',
        axis,
      ),
      d(
        'tailgate',
        'Restricted-side close-following',
        'Video candidate',
        'Critical',
        'restricted-door',
        'Two tracks cross a restricted-side door within a short interval on one credential event.',
        'Crew moving as a group is legitimate and looks identical without access data.',
        'Correlate with the access event and challenge at the door.',
        axis,
      ),
      d(
        'intrusion',
        'Perimeter or airside intrusion',
        'Video candidate',
        'Critical',
        'transit-fence',
        'A track crosses an approved boundary line.',
        'Wildlife, weather and maintenance crews create false candidates; a crossing does not establish intent.',
        'Dispatch the response team and hold movements as required.',
        axis,
      ),
      d(
        'escalator',
        'Escalator incident / pile-up',
        'Video candidate',
        'High',
        'escalator-landing',
        'A person-down candidate or abnormal accumulation appears at an escalator landing.',
        'Luggage handling and crowding produce similar patterns. Not a mechanical fault diagnosis.',
        'Stop the escalator and send first aid.',
        hanwha,
      ),
      d(
        'fall',
        'Fall / person down',
        'Video candidate',
        'High',
        'escalator-landing',
        'A posture transition or person-down candidate in a public area.',
        'Sitting on floors, prayer and children playing confuse the model.',
        'Send first aid and record the incident.',
        hanwha,
      ),
      d(
        'dwell',
        'Prolonged dwell in a sensitive area',
        'Video candidate',
        'Medium',
        'taxi-rank',
        'A track remains in a sensitive zone beyond a dwell limit.',
        'Waiting, disability, delay and meeting arrivals are normal explanations. Never label a person suspicious.',
        'Offer assistance first; escalate only on an observed problem.',
        axis,
      ),
      d(
        'kerbside',
        'Kerbside vehicle dwell',
        'Video candidate',
        'Medium',
        'taxi-rank',
        'A vehicle remains in a set-down area beyond its permitted period.',
        'Assisted boarding legitimately takes longer; perspective is not a calibrated measurement.',
        'Ask the marshal to move the vehicle on.',
        axis,
      ),
      d(
        'exit',
        'Blocked emergency exit',
        'Video candidate',
        'High',
        'transit-concourse',
        'A persistent scene change appears in a marked escape route.',
        'Not a certified fire-safety inspection; retail and cleaning equipment move constantly.',
        'Clear the route and record the check.',
        ipro,
      ),
      d(
        'smoke',
        'Smoke / flame warning',
        'Sensor integration',
        'Critical',
        'transit-platform',
        'An approved fire device or specialist video system sends a warning.',
        'Ordinary CCTV is not an approved fire detection system; evacuation of a full concourse is slow.',
        'Follow the station evacuation plan.',
        bosch,
      ),
      ...serviceHealth(
      'restricted-door', 'Dispatch a patrol and log the coverage gap.'),
      d(
        'disruptive',
        'Disruptive passenger report',
        'Staff report',
        'High',
        'gate-hold',
        'A staff member records abuse, threat or disruptive conduct.',
        'A reporting category, not an added detector. Under-reporting is common.',
        'Support the staff member and follow the escalation policy.',
        workflow,
      ),
      d(
        'lostchild',
        'Unaccompanied child or vulnerable passenger',
        'Staff report',
        'Critical',
        'security-queue',
        'A staff member or member of the public raises a concern.',
        'No facial matching or watchlist search is enabled. Human search and control-room coordination are the method.',
        'Initiate the safeguarding and reunification procedure.',
        workflow,
      ),
      d(
        'nearmiss',
        'Operational near miss',
        'Staff report',
        'High',
        'escalator-landing',
        'Staff record a near miss on a platform, apron or concourse.',
        'A reporting category, not an added detector.',
        'Investigate and feed into the safety management system.',
        workflow,
      ),
    ],
    excluded: [
      {
        name: 'Facial recognition and watchlist matching',
        why: 'Real-time biometric identification in publicly accessible spaces is high-risk under the EU AI Act and sensitive personal data under the amended PDPA. Lawful border-control systems are operated by the authority, not by this platform.',
      },
      {
        name: 'Behaviour-based "hostile intent" prediction',
        why: 'No validated basis, and false positives fall hardest on people who are already profiled.',
      },
      {
        name: 'Ethnicity, appearance or clothing-based filtering',
        why: 'Discriminatory by construction.',
      },
      {
        name: 'Automatic armed or police dispatch from an unattended-item alert',
        why: 'The overwhelming majority of unattended bags are forgotten luggage. A human assesses.',
      },
      {
        name: 'Cameras in toilets, prayer rooms or search booths',
        why: 'A reasonable expectation of privacy applies absolutely, and a search booth is already supervised by the officer conducting the search.',
      },
    ],
    keyRisks: [
      'Crowd density and crush risk at peak and during disruption',
      'Platform-edge incidents',
      'Restricted-side access control integrity',
      'Unattended items causing service-wide disruption',
    ],
    sites: ['KL Sentral Interchange', 'Seremban Transit Terminal'],
    modules: ['pilot-governance', 'platform-readiness'],
    presence: false,
  },

  // ------------------------------------------------------------------ 8
  {
    id: 'commercial',
    name: 'Commercial property',
    sector: 'Office towers and corporate campuses',
    tagline:
      'Access integrity, occupancy and emergency readiness across managed buildings.',
    lexicon: {
      site: 'building',
      sitePlural: 'buildings',
      siteTitle: 'Building',
      person: 'occupant',
      personPlural: 'occupants',
      staff: 'building team',
      reviewTeam: 'Building control room',
      hours: 'Core hours',
    },
    regulator:
      'Uniform Building By-Laws · Fire Services Act 1988 · PDPA',
    zones: [
      'Ground lobby',
      'Turnstile line',
      'Lift lobby',
      'Car park',
      'Loading dock',
      'Plant room corridor',
      'Roof access',
      'Site perimeter',
    ],
    privateZones: [
      'Toilets and shower rooms',
      'Prayer rooms',
      'Nursing rooms',
      'Tenant demised space',
    ],
    categories: [
      'Turnstile tailgating',
      'After-hours presence',
      'Restricted plant access',
      'Occupancy pressure',
      'Perimeter intrusion',
      'Loading dock conflict',
      'Unattended item',
      'Blocked exit',
      'Person down',
      'Reception aggression',
    ],
    capabilities: [
      d(
        'tailgate',
        'Turnstile close-following',
        'Video candidate',
        'High',
        'turnstile-line',
        'Two tracks pass a turnstile or speedgate on one credential event.',
        'Assisted access, deliveries and accessibility gates are legitimate and look identical without access data.',
        'Correlate with the access event and challenge at reception.',
        axis,
      ),
      d(
        'afterhours',
        'After-hours presence',
        'Video candidate',
        'Medium',
        'office-lobby',
        'Presence is detected in a common area during a closed period.',
        'Cleaning, security rounds and permitted tenant works are scheduled exceptions.',
        'Verify against the out-of-hours works register.',
        axis,
      ),
      d(
        'plant',
        'Plant room or roof access entry',
        'Video candidate',
        'High',
        'turnstile-line',
        'A track enters a plant room corridor or roof access outside a maintenance window.',
        'Authorised engineers use the same route; the permit system is the source of truth.',
        'Verify the permit to work before responding.',
        axis,
      ),
      d(
        'occupancy',
        'Occupancy & space utilisation',
        'Video candidate',
        'Medium',
        'turnstile-line',
        'Anonymous counts of people present in a common area over time.',
        'An estimate from a known view. It is not an attendance record and must never be attributed to a person or a team.',
        'Use for space planning, cleaning and HVAC scheduling only.',
        axis,
      ),
      d(
        'muster',
        'Evacuation flow & muster support',
        'Video candidate',
        'High',
        'office-lobby',
        'Anonymous egress counts at exits and muster points during an evacuation.',
        'Counts drift when exits are unobserved. This supports the fire warden; it is never an evacuation headcount or a roll call.',
        'Give the warden the flow picture; the roll call remains manual.',
        axis,
      ),
      d(
        'intrusion',
        'Perimeter intrusion',
        'Video candidate',
        'High',
        'office-perimeter',
        'A track crosses an approved boundary line outside operating hours.',
        'Wildlife, weather and neighbouring activity create false candidates.',
        'Verify and dispatch the on-call response.',
        axis,
      ),
      d(
        'dock',
        'Loading dock vehicle / pedestrian conflict',
        'Video candidate',
        'High',
        'office-carpark',
        'A pedestrian track enters a marked vehicle movement area at the dock.',
        'Perspective is not a calibrated distance or speed measurement.',
        'Separate traffic and pedestrians; review the dock marshalling plan.',
        axis,
      ),
      d(
        'left',
        'Unattended item in a public area',
        'Video candidate',
        'Medium',
        'lift-lobby',
        'An object remains after the person who placed it leaves the view.',
        'Cannot determine ownership or contents. Deliveries and lost property are the common cases.',
        'Follow the lost-property and security protocol.',
        ipro,
      ),
      d(
        'exit',
        'Blocked fire exit',
        'Video candidate',
        'High',
        'plant-corridor',
        'A persistent scene change appears in a marked escape route.',
        'Not a certified fire-safety inspection; fit-out works move material constantly.',
        'Clear the route and record it against the statutory check.',
        ipro,
      ),
      d(
        'fall',
        'Fall / person down',
        'Video candidate',
        'High',
        'office-carpark',
        'A posture transition or person-down candidate in a common area.',
        'Crouching, sitting on floors and maintenance work confuse the model.',
        'Send first aid and record the incident.',
        hanwha,
      ),
      d(
        'aggression',
        'Aggression at reception',
        'Video candidate',
        'High',
        'office-lobby',
        'Rapid close interaction at a reception or security desk.',
        'Motion cannot establish intent or threat. Animated conversation looks similar.',
        'Send support and protect the reception team.',
        nnu,
      ),
      d(
        'lone',
        'Lone worker after hours',
        'Video candidate',
        'Medium',
        'office-perimeter',
        'A single track is present in a common area outside staffed hours.',
        'Presence is not distress; permitted works are legitimate.',
        'Make contact and confirm welfare.',
        axis,
      ),
      d(
        'doorheld',
        'Secure door held open',
        'Sensor integration',
        'Medium',
        'office-dock',
        'A door contact on a controlled boundary remains open beyond its allowed period.',
        'Requires a real door contact. Deliveries create legitimate exceptions.',
        'Check the door and the approved delivery schedule.',
        ipro,
      ),
      d(
        'smoke',
        'Smoke / flame warning',
        'Sensor integration',
        'Critical',
        'plant-corridor',
        'An approved fire device or specialist video system sends a warning.',
        'Ordinary CCTV is not an approved fire detection system.',
        'Follow the building fire and evacuation procedure.',
        bosch,
      ),
      ...serviceHealth(
      'roof-access', 'Arrange a patrol and maintenance check.'),
      d(
        'defect',
        'Building defect report',
        'Staff report',
        'Medium',
        'plant-corridor',
        'A tenant or engineer reports a defect affecting safety or access.',
        'A reporting category, not an added detector.',
        'Raise a maintenance task and restrict the area if unsafe.',
        workflow,
      ),
      d(
        'visitor',
        'Visitor or contractor concern',
        'Staff report',
        'Medium',
        'office-dock',
        'Reception records an access or conduct concern.',
        'No facial matching or visitor watchlist is enabled.',
        'Follow the visitor management and escalation policy.',
        workflow,
      ),
      d(
        'incident',
        'Security incident report',
        'Staff report',
        'High',
        'roof-access',
        'The building team records an incident for investigation.',
        'A reporting category, not an added detector.',
        'Investigate and update the security operating procedure.',
        workflow,
      ),
    ],
    excluded: [
      {
        name: 'Facial recognition of occupants, tenants or visitors',
        why: 'Biometric data is sensitive personal data under the amended PDPA, and access control already solves identity with a credential.',
      },
      {
        name: 'Individual movement tracking or desk-level attendance',
        why: 'Occupancy analytics is legitimate in aggregate; following a named person around a building is not.',
      },
      {
        name: 'Employee productivity or presence scoring',
        why: 'Not a safety control, and it destroys tenant trust.',
      },
      {
        name: 'Emotion inference at reception',
        why: 'No validated basis, and a visitor who reads as agitated to a model is most often simply late, unwell or unfamiliar with the building.',
      },
      {
        name: 'Cameras in toilets, prayer rooms, nursing rooms or demised tenant space',
        why: 'Never proportionate, and demised space is not the landlord’s to monitor.',
      },
    ],
    keyRisks: [
      'Access control defeated by tailgating at turnstiles',
      'Unauthorised plant room and roof access',
      'Escape route obstruction during fit-out works',
      'Loading dock vehicle and pedestrian conflict',
    ],
    sites: ['Menara Seremban', 'Cyberjaya Corporate Campus'],
    modules: ['pilot-governance', 'platform-readiness'],
    presence: false,
  },
];

export const industryIds = industries.map((i) => i.id);

export function getIndustry(id: string): Industry {
  return industries.find((i) => i.id === id) ?? industries[0];
}

/** Capability register for an industry, optionally filtered by kind. */
export function industryCapabilities(id: string, kind = 'All') {
  const caps = getIndustry(id).capabilities;
  return kind === 'All' ? caps : caps.filter((c) => c.kind === kind);
}

/**
 * A saved rule must sit in a monitorable zone for the selected industry and
 * must never be placed in a zone the industry excludes.
 */
export function industryZoneError(id: string, zone: string, publicOnly: boolean) {
  const industry = getIndustry(id);
  if (industry.privateZones.includes(zone))
    return `${zone} is excluded from camera monitoring in ${industry.name.toLowerCase()}.`;
  if (!industry.zones.includes(zone) || !publicOnly)
    return 'Only approved monitored areas are available for this demonstration.';
  return '';
}

/** Counts used by the industry profile screen. */
export function capabilityMix(id: string) {
  const caps = getIndustry(id).capabilities;
  const by = (k: DetectionCapability['kind']) =>
    caps.filter((c) => c.kind === k).length;
  return {
    total: caps.length,
    video: by('Video candidate'),
    sensor: by('Sensor integration'),
    report: by('Staff report'),
    critical: caps.filter((c) => c.priority === 'Critical').length,
    excluded: getIndustry(id).excluded.length,
  };
}
